import { Geist, Geist_Mono , Roboto } from "next/font/google";
import "./globals.css";
import SidebarComponent from "@/components/SidebarComponent";
import Navbar from "@/components/NavbarComponent";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Barça ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${roboto.variable} h-full antialiased`}
    >
      <body
        className={`${roboto.variable} antialiased flex flex-col h-screen `}
      >
        <div>
            
          <SidebarComponent>
              {children}
          </SidebarComponent>
        </div>
       
      </body>
    </html>
  );
}
